baseurl = "https://postgres.rest/"
languageCode = "en-us"
metadataformat = "yaml"
title = "pREST"
theme = "hugo-theme-learn"

disqusShortname = ""
googleAnalytics = "UA-105743002-1"

[params]
name = "pREST"
description = "A fully RESTful API from any existing PostgreSQL database."
github_user = "prest"
github_repo = "prest"
github_banner = true
custom_css = []
custom_js = []
highlightjs = "css/highlight.css"
favicon = "favicon.ico"
editURL = "https://github.com/prest/prest.github.io/tree/master/content/"
showVisitedLinks = true
logo = "logo.png"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params.sidebar]
github_button  = true
travis_button  = true
codecov_button = true
gratipay = ""
show_relations = true

[params.footer]
copyright = "[pREST](https://postgres.rest/)"
show_powered_by = true

[Languages]
[Languages.en]
title = "Documentation for pREST"
weight = 1
languageName = "English"
